### PR TITLE
added german translation

### PR DESCRIPTION
**Pull request by J0Ar**

### CODE REVIEW

**Comment by lainsce** [comment]
Why are there two PRs? 😉

**Comment by J0Ar** [comment]
:fearful:   Because...aah...i'm still new to this and...i don't know!? 
**First** i created a new de.po file and **second** i changed the LINGUAS-file (added de)
Is it possible to do this in a single pull request?

I'm really new to this and have to figure out...sorry :see_no_evil:

**Comment by lainsce** [comment]
It is possible! Just use your defined patch-1 branch as you've made, and add the LINGUAS file there. Then push your changes to that branch.

**Comment by lainsce** [comment]
Just this time though, I'll add in your two branches. 😄

**Comment by J0Ar** [comment]
Ok, thank you lainsce. Sorry because of the additional effort you had. 
I managed these 2 files in my browser and did it in two separate tabs. It was the first time i made a change and pull request...with all these confusing buttons and terms. 😕 
But for this first time i'm really proud of myself to got it managed...even if it was a bit complicated. 😆 
Next time I know better, because I tried it in my own branch and you know what...you're right about being able to do several things at once. 😅 See ya ✋

**Pull request merged**
