### PR TITLE
Joan translated your app for ca

### PR DESCRIPTION
**Pull request by JoanGitHubUser**
Hi,
  This is the translation to ca (catalan) language. I have tried to compile Quilter and install it on my system to proper revision, but the ninja installation have failed on my system  in this sentence: 

../src/Widgets/SideBar.vala:40.16-40.23: error: The type name `Hdy.Flap' could not be found
        public Hdy.Flap flap;
               ^^^^^^^^
Compilation failed: 1 error(s), 0 warning(s)
 
  Best regards,
     Joan

### CODE REVIEW

**Comment by lainsce** [comment]
Don't worry about that compilation error, distributions have an outdated libhandy (which in a newer version has Hdy.Flap) package.

**Comment by lainsce** [comment]
Some things:

- Don't forget to add "ca" to the LINGUAS file
- Don't forget to remove those .swp and .mo files.

**Comment by JoanGitHubUser** [comment]
Some things:

Don't forget to add "ca" to the LINGUAS file

  -> "ca" language is already in the LINGUAS file. Not in the last place but in the first.
 
Don't forget to remove those .swp and .mo files.

  -> I will try to remove them and commit again

**Comment by lainsce** [comment]
>  "ca" language is already in the LINGUAS file. Not in the last place but in the first.

Oh didn't see it there, oops.

All looks good. Merging.

**Comment by JoanGitHubUser** [comment]
Branch deleted.

**Comment by lainsce** [comment]
It's alright to delete once merged :)

**Pull request merged**
