### PR TITLE
Focus only current sentence

### PR DESCRIPTION
**Pull request by wyhasany**
Focusing only current sentence gives much better results.
Last version of application could highlight 1 line back. It could
focus all paragraph instead only current sentence.

I hope so that you'll like this feature!

Focus before:
selection_007

Focus right now:
selection_006

### CODE REVIEW

**Comment by lainsce** [comment]
Can you upgrade this with a setting on the preferences to choose between sentence and paragraph?
Check out how I do the margins preference in the code to see how it's done.
This would be very appreciated. :)

**Comment by wyhasany** [comment]
I am really beginner, but I'll try to do it ;)

**Comment by lainsce** [comment]
If you have any questions, feel free to ask them here :D

**Comment by wyhasany** [comment]
If you can recommend some handy tools for developing in vala it would be highly appreciated. I've started with Gnome Builder + Vim

**Comment by lainsce** [comment]
I myself, use elementary Code (_nee_ Scratch), and I do git stuff and build stuff on the terminal.

**Comment by lainsce** [comment]
Congrats! You've done it perfectly! :tada: :tada: :tada:  
If you've liked using Vala like this, why not make an app of your own, or contribute to elementary OS projects? :)  
I made this challenge of sorts to show you how Vala is like. Did you like coding in it? :thinking:

**Comment by wyhasany** [comment]
Ok! It works correctly right now. I think that Vala is very cool language (this is my first impression). I don't have good idea for new application for ElementaryOS but I would like to add some features like this one to some applications. Especially to that one ;)

gifout

**Comment by lainsce** [comment]
By the way, you got a special mention in the update, which is going to show in AppCenter when a new version is there. :tada:

**Comment by wyhasany** [comment]
Thank you so much! :+1:

**Pull request merged**
