### PR TITLE
Created travis.yml file to support travis build.

### PR DESCRIPTION
**Pull request by harisvsulaiman**
Builds the app on travis in the same environment as appcenter.

### CODE REVIEW

**Comment by harisvsulaiman** [comment]
https://github.com/harisvsulaiman/element-build

**Comment by lainsce** [comment]
Thanks!

**Comment by harisvsulaiman** [comment]
@lainsce hopefully you can integrate build with all your apps. :-)

**Comment by lainsce** [comment]
I'll see how it's done and do it on them ;)

**Pull request merged**
